services:
  - type: web
    name: alice-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node start-render.js
    healthCheckPath: /health
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
